sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Dlt@112102

  minio:
    access-key: Ab0xl76UnvCldbbwzhiD
    secret-key: 8MIwu3FIIDkrFBP1Dqhs3pKo6XqLxa8h9T9rP9OY
    bucket: sky-take-out
    end-point: http://nas.boeing773er.site:9000
    read-path: http://nas.boeing773er.site:9000

  redis:
    host: localhost
    port: 6379
    password: Dlt@112102
    database: 2

  wechat:
    appid: wx761a92e990d4c336
    secret: 4ae28f5c58c1d4690905a5a894414c51